#!/bin/bash
if [ ! -d "node_modules" ]; then
  ln -s "$(git rev-parse --show-toplevel)/node_modules" node_modules 2>/dev/null
fi
if [ ! -f ".env.local" ]; then
  cp "$(git rev-parse --show-toplevel)/.env.local" .env.local 2>/dev/null
fi
